image: node:latest

cache:
    paths:
        - node_modules/

build:
    stage: build
    script:
        - npm ci
        - npm run build
    artifacts:
        paths:
            - ./target

diff:
    stage: test
    script: npm run cdk diff
    artifacts:
        paths:
            - ./target
